import { Comment } from "../comment/Comment";

export type Post = {
  author: string | null;
  blogAuthor: string | null;
  blogContent: string | null;
  bodyContent: string | null;
  comments?: Array<Comment>;
  content: string | null;
  createdAt: Date;
  createdTimestamp: Date | null;
  creationDate: Date | null;
  creationDateTime: Date | null;
  creationTimestamp: Date | null;
  headline: string | null;
  id: string;
  modificationDate: Date | null;
  modificationDateTime: Date | null;
  modificationTimestamp: Date | null;
  postAuthor: string | null;
  postBody: string | null;
  postContent: string | null;
  postCreationDate: Date | null;
  postModificationDate: Date | null;
  postTitle: string | null;
  postWriter: string | null;
  title: string | null;
  updatedAt: Date;
  updatedTimestamp: Date | null;
  writer: string | null;
};
